# Site settings
title: Lee - ̗̀(●▽● ) ̖́-
email: leesavide@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ᕕ( ●▽●)ᕗ I am not on fire!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leesavide.github.io" # the base hostname & protocol for your site
twitter_username: lewdlime
github_username:  leesavide
gems: ["jekyll", "jekyll-compose", "jekyll-mentions", "jemoji", "jekyll-redirect-from", "jekyll-sitemap", "jekyll-feed"]
# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]
permalink: /:path/
include: ['_pages']
exclude: ['vendor', 'cibuild']

collections:
  music:
    permalink: /music/:path/
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Lee Savide"
  -
    scope:
      path: "/about-mdl/"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "LICENSE.html"
      type: "pages"
    values:
      layout: "page"

more_vert:
  option1:
    name: About
    link: "/about-mdl/"
  option2:
    name: License
    link: "/LICENSE.html"

disqus: true
disqus_shortname: 'leesavide'

# Build settings
markdown: kramdown
