# Site settings
title: Lee - ̗̀(●▽● ) ̖́-
email: leesavide@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ᕕ( ●▽●)ᕗ I am not on fire!
baseurl: ""
url: "http://leesavide.github.io"
twitter_username: lewdlime
github_username:  leesavide
gems: ["jekyll", "jekyll-compose", "jekyll-mentions", "jemoji", "jekyll-redirect-from", "jekyll-sitemap", "jekyll-feed"]

header_type: default
post_type: highlight
pagination_type: default
permalink: /:path/
include: ['_pages']
exclude: ['vendor', 'cibuild']

collections:
  music:
    permalink: /music/:path/
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Lee Savide"
  -
    scope:
      path: "/about-mdl/"
      type: "pages"
    values:
      layout: "page"

more_vert:
  option1:
    name: Home
    link: {{site.url}}
  option2:
    name: About
    link: "/about-mdl/"
  option3:
    name: Music
    link: "/music/"

disqus: true
disqus_shortname: 'leesavide'

# Build settings
markdown: kramdown
